---
functional: 
- Пользователь должен иметь возможность зарегистрироваться на сайте
- Nickname при регистрации должен состоять от 3 до 16 латинских букв. Так же могут быть добавлены цифры и знак нижнего подчеркивания
- Email при регистрации должен быть валидируемым
- Password должен быть от 6 до 16 букв или цифр. Обязательно должен быть минимум один специальный символ
- При верном вводе Email и Password, зарегистрированный пользователь должен войти на сайт
- Пользователь должен иметь возможность выбрать регистрацию через GitHub
- Пользователь должен иметь возможность выбрать регистрацию через Discord
- Пользователь должен иметь возможность принять участие в игре без регистрации
- Пользователь должен иметь возможность восстановить пароль
- Пользователь должен иметь возможность войти в личный кабинет
- Пользователь должен иметь возможность выйти из личного кабинета
- Пользователь должен иметь возможность создать игру 
- Пользователь должен иметь возможность выбрать во время игры язык программирования
- Проверка на возможность во время игры просматривать задачу на английском и русском языках
- Пользователь должен иметь возможность во время игры проверить решение
- Пользователь должен иметь возможность во время игры просматривать свой редактор кода и редактор соперника
- Пользователь должен иметь возможность просмотреть повтор игры
- Пользователь должен иметь возможность сдаться во время игры
non-functional:
- Сайт должен быть разработан с учетом удобства использования и оптимизирован для скорости работы
- Сайт должен быть безопасным и защищать данные пользователя
- Сайт должен быть удобным на мобильном устройстве
- Сайт должен быть протестирован на совместимость с последними версиями браузеров
- Сайт должен быть способен обрабатывать большое количество трафика (например, 1000 одновременных пользователей)
implicit:
- Интерфейс сайта должен быть интуитивно понятным, чтобы новые пользователи могли легко начать использовать приложение без необходимости изучать документацию
- Пользователь может иметь возможность настроить игровой интерфейс под свои предпочтения или адаптировать под свой уровень игры
- Интеграция с социальными сетями, возможность делиться результатами или приглашать друзей на соревнования
