---
functional: 
- Пользователь должен иметь возможность зарегистрироваться на сайте
- Пользователь должен иметь возможность выбрать регистрацию через GitHub
- Пользователь должен иметь возможность выбрать регистрацию через Discord
- Пользователь должен иметь возможность принять участие в игре без регистрации
- Пользователь должен иметь возможность восстановить пароль
- Пользователь должен иметь возможность войти в личный кабинет
- Пользователь должен иметь возможность выйти из личного кабинета
- Пользователь должен иметь возможность создать игру 
- Пользователь должен иметь возможность выбрать во время игры язык программирования
- Проверка на возможность во время игры просматривать задачу на английском и русском языках

