---
functional: 
- Пользователь должен иметь возможность зарегистрироваться на сайте
- Nickname при регистрации должен состоять от 3 до 16 латинских букв. Так же могут быть добавлены цифры и знак нижнего подчеркивания
- Email при регистрации должен быть валидируемым
- Password должен быть от 6 до 16 букв или цифр. Обязательно должен быть минимум один специальный символ
- При верном вводе Email и Password, зарегистрированный пользователь должен войти на сайт
- Пользователь должен иметь возможность выбрать регистрацию через GitHub
- Пользователь должен иметь возможность выбрать регистрацию через Discord
- Пользователь должен иметь возможность принять участие в игре без регистрации
- Пользователь должен иметь возможность выбрать авторизацию через GitHub
- Пользователь должен иметь возможность выбрать авторизацию через Discord
- При вводе неправильного Email или Password пользователь должен получить сообщение об ошибке
- Пользователь должен иметь возможность восстановить пароль
- Пользователь должен иметь возможность просматривать личный кабинет
- Пользователь должен иметь возможность выйти из личного кабинета
- При переключении между вкладками WEEK, MONTH, ALL список рейтинга обновляется и отображается в правильном порядке
- Пользователь должен иметь возможность создать игру
- Пользователь должен иметь возможность менять критерии при создании игры
- Пользователь должен иметь возможность смотреть гайд по функциям приложения во время игры
- Пользователь должен иметь возможность во время игры сбросить решение и вернуть исходный код
- Пользователь должен иметь возможность писать в чат во время игры
- Пользователь должен иметь возможность во время активной игры совершить переход на главную страницу и вернуться обратно в игру
- Пользователи должны иметь возможность запустить игру заново
- Пользователь должен иметь возможность приглаать в игру друга
- Пользователь должен иметь возможность отменить приглашение в игру
- Пользователь должен иметь возможность принимать приглашение на игру от другого игрока
- Пользователь должен иметь возможность отклонять приглашение на игру от другого игрока
- Пользователь должен иметь возможность выбрать во время игры язык программирования
- Проверка на возможность во время игры просматривать задачу на английском и русском языках
- Пользователь должен иметь возможность во время игры проверить решение
- Пользователь должен иметь возможность во время игры просматривать свой редактор кода и редактор соперника
- Пользователь должен иметь возможность просмотреть повтор игры
- Пользователь должен иметь возможность сдаться во время игры
- Пользователь должен иметь возможность выиграть игру
- Пользователь должен иметь возможность просматривать рейтинг пользователей
- Рейтинг должен отображаться корректно при сортировке по возрастанию и убываю разных критериев
- Количество строк рейтинга должно отображаться правильно относительно указанного количества 
- Пользователь должен иметь возможность искать конкретного пользователя в списке рейтинга
- Пользователь должен иметь возможность просматривать информацию о турнирах
- Пользователь должен иметь возможность создать турнир
- Пользователь должен иметь возможность просматривать задачи
- Пользователь должен иметь возможность создать новую задачу
- Пользователь должен иметь возможность изменить свои данные в личном кабинете
- Пользователь должен иметь возможность просматривать исходный код игры наGithab
- Пользователь должен иметь возможность перейти в сообщество игры в Discord
- Пользователь должен иметь возможность из личного кабинета перейти на сайт Hexlеt
- Пользователь должен иметь возможность перейти в сообщество игры в телеграм канале
non-functional:
- Сайт должен быть разработан с учетом удобства использования и оптимизирован для скорости работы
- Сайт должен быть безопасным и защищать данные пользователя
- Сайт должен быть удобным на мобильном устройстве
- Сайт должен быть протестирован на совместимость с последними версиями браузеров
- Сайт должен быть способен обрабатывать большое количество трафика (например, 1000 одновременных пользователей)
implicit:
- Интерфейс сайта должен быть интуитивно понятным, чтобы новые пользователи могли легко начать использовать приложение без необходимости изучать документацию
- Пользователь может иметь возможность настроить игровой интерфейс под свои предпочтения или адаптировать под свой уровень игры
- Интеграция с социальными сетями 
- Возможность делиться результатами или приглашать друзей на соревнования
